### ISSUE TITLE
a range error when compiling with Delphi 10.4

### ISSUE THREAD

**Issue by dkounal** [SynEdit/SynEdit#157]
It just needs a zero before to file SynEdit\Source\SynHighlighterECMAScript.pas

@ -740,7 +740,7 @@ begin
 instread of   #$F8..#$2C1:
must be:   #$0F8..#$2C1:

@ -826,7 +826,7 @@ function TSynECMAScriptSyn.IsIdentChar(AChar: WideChar): Boolean;
instead of:   #$F8..#$2C1:
must be:   #$0F8..#$2C1:

**Comment by jaclas** [comment]
In 10.3 too... :-(

**Comment by CWBudde** [comment]
I have merged the pull request. It should work now (haven't checked though, as I don't have a recent Delphi version at hand)

**Comment by jaclas** [comment]
I still get compilation error

![image](https://user-images.githubusercontent.com/17312717/106611713-93773780-6568-11eb-90ba-78471b3665fc.png)

I try on latest version of SynEdid and Delphi 10.3

**Comment by lemonlittlebaby** [comment]
> I still get compilation error
> 
> ![image](https://user-images.githubusercontent.com/17312717/106611713-93773780-6568-11eb-90ba-78471b3665fc.png)
> 
> I try on latest version of SynEdit and Delphi 10.3

How to fix it?I got same error.

**Comment by PTlaowai** [comment]
Can you try again with all the hex values having a 0 or 00 prefix?
e.g. #$00AA, #$00AA,$00C0.. (etc)
Does it compile this time?

**Comment by jaclas** [comment]
In the meantime, I have abandoned Delphi and am now programming in other environments and languages, but I received notification of this ticket. And I do not hide my astonishment that it still has not been corrected! I first encountered this a decade ago. The problem is trivial to correct, the lack of a fix is unbelievable.
